# Generated by Django 3.1.5 on 2021-01-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
