# Generated by Django 3.2.4 on 2021-09-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='position',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
