# Generated by Django 3.1.5 on 2021-09-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20210916_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
